version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_URI
    depends_on:
      - db
    links:
      - db
    ports:
      - 8080:8080
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
